version: "3.9"
services:
  myapp:
    build: .
    ports:
      - "8080:8080" # Adjust port mappings if needed
    restart: always # Restart the container if it crashes or stops
    network_mode: "host" # Use the host's network stack for the container
    
