version: "3.9"
services:
  myapp:
    build: .
    ports:
      - "8080:8080" # Adjust port mappings if needed
    restart: always # Restart the container if it crashes or stops
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows accessing host from container
    
